# -*- coding: utf-8 -*-
"""init.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18VY8R2fvvy3gEcGgx30biKMQo3aDFqzs
"""

from flask import Flask

# Initialize Flask App
app = Flask(__name__)

# Import routes
from app import routes