# -*- coding: utf-8 -*-
"""routes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18VY8R2fvvy3gEcGgx30biKMQo3aDFqzs
"""

from flask import request, jsonify
from app import app
from app.model_loader import h2o_model
import h2o

@app.route('/predict', methods=['POST'])
def predict():
    """Endpoint for making predictions."""
    try:
        # Get JSON data from request
        data = request.json

        # Convert JSON data to H2OFrame
        input_frame = h2o.H2OFrame([data])

        # Make prediction
        prediction = h2o_model.predict(input_frame)
        result = int(prediction[0, 0])

        # Return prediction result
        return jsonify({'prediction': result})
    except Exception as e:
        return jsonify({'error': str(e)}), 500