# -*- coding: utf-8 -*-
"""config.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18VY8R2fvvy3gEcGgx30biKMQo3aDFqzs
"""

import os

# AWS S3 Configuration
S3_BUCKET = os.getenv('S3_BUCKET', 'my-automl-bucket')
S3_MODEL_KEY = os.getenv('S3_MODEL_KEY', 'trained_model.zip')
LOCAL_MODEL_PATH = 'models/trained_model.zip'

# Flask App Configuration
HOST = '0.0.0.0'
PORT = 5000